var sourceData = [
    {
        id: 1,
        description: "Manchester United Football Club, commonly referred to as Man United (often stylised as Man Utd), or simply United, is a professional football club based in Old Trafford, Greater Manchester, England. The club competes in the Premier League, the top division in the English football league system.",
        name: "Manchester United",
        your_support: "$220",
        all_support: "1625",
        current: true,
        league: "Premier League, UK",
        image: "https://logos-world.net/wp-content/uploads/2020/06/Manchester-United-logo.png",
    },
    {
        id: 2,
        description: "2-Manchester United Football Club, commonly referred to as Man United (often stylised as Man Utd), or simply United, is a professional football club based in Old Trafford, Greater Manchester, England. The club competes in the Premier League, the top division in the English football league system.",
        name: "Liverpool",
        your_support: "$250",
        all_support: "1625",
        current: true,
        league: "Premier League, UK",
        image: "https://logos-world.net/wp-content/uploads/2020/06/Manchester-United-logo.png",
    },
    {
        id: 3,
        description: "3-Manchester United Football Club, commonly referred to as Man United (often stylised as Man Utd), or simply United, is a professional football club based in Old Trafford, Greater Manchester, England. The club competes in the Premier League, the top division in the English football league system.",
        name: "Liverpool",
        your_support: "$250",
        all_support: "1625",
        current: true,
        league: "Premier League, UK",
        image: "https://logos-world.net/wp-content/uploads/2020/06/Manchester-United-logo.png",
    },
    {
        id: 4,
        description: "4-Manchester United Football Club, commonly referred to as Man United (often stylised as Man Utd), or simply United, is a professional football club based in Old Trafford, Greater Manchester, England. The club competes in the Premier League, the top division in the English football league system.",
        name: "Liverpool",
        your_support: "$250",
        all_support: "1625",
        current: true,
        league: "Premier League, UK",
        image: "https://logos-world.net/wp-content/uploads/2020/06/Manchester-United-logo.png",
    },
    {
        id: 5,
        description: "5-Manchester United Football Club, commonly referred to as Man United (often stylised as Man Utd), or simply United, is a professional football club based in Old Trafford, Greater Manchester, England. The club competes in the Premier League, the top division in the English football league system.",
        name: "Liverpool",
        your_support: "$250",
        all_support: "1625",
        current: true,
        league: "Premier League, UK",
        image: "https://logos-world.net/wp-content/uploads/2020/06/Manchester-United-logo.png",
    },
];